apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        env:
        - name: secret
          valueFrom:
            secretKeyRef:
              name: secret
              key: secret        